---
# Ansible playbook to configure a Raspberry Pi speed camera.
# Usage:
#   ansible-playbook playbooks/setup.yaml

- name: Configure speed camera Raspberry Pi
  hosts: all
  become: true

  roles:
    - system
    - rustup
    - speedcam
